@startwbs
* UML workflow
** first is the ledgerIO puml file\nDONE
** 2nd is the EventHandler puml file\nStarted
** 3rd is the StratInterface puml file\nNot Started
** 4th is the Log Puml file\nNot Started
@endWBS